export const fakeservice = [
  {
    id: 1,
    name: "Sifaka, verreaux's",
    type: "americanexpress",
    worth: "$189.95",
    supplierName: "Pouros Group",
    createAt: "5/12/2021",
  },
  {
    id: 2,
    name: "Blue peacock",
    type: "visa",
    worth: "$512.12",
    supplierName: "Klocko LLC",
    createAt: "7/13/2021",
  },
  {
    id: 3,
    name: "Southern lapwing",
    type: "americanexpress",
    worth: "$353.97",
    supplierName: "McClure, Dooley and Lebsack",
    createAt: "12/1/2020",
  },
  {
    id: 4,
    name: "White-nosed coatimundi",
    type: "visa",
    worth: "$476.34",
    supplierName: "Bechtelar Group",
    createAt: "12/27/2020",
  },
  {
    id: 5,
    name: "Quoll, eastern",
    type: "americanexpress",
    worth: "$547.52",
    supplierName: "Hand-Rodriguez",
    createAt: "1/29/2021",
  },
  {
    id: 6,
    name: "Sulfur-crested cockatoo",
    type: "mastercard",
    worth: "$761.45",
    supplierName: "Hyatt-Nitzsche",
    createAt: "1/13/2021",
  },
  {
    id: 7,
    name: "Elephant, asian",
    type: "americanexpress",
    worth: "$99.89",
    supplierName: "Parker-Walker",
    createAt: "6/21/2021",
  },
  {
    id: 8,
    name: "Coke's hartebeest",
    type: "mastercard",
    worth: "$918.73",
    supplierName: "Spinka LLC",
    createAt: "7/26/2021",
  },
  {
    id: 9,
    name: "Painted stork",
    type: "americanexpress",
    worth: "$911.07",
    supplierName: "Bergnaum-Waters",
    createAt: "12/22/2020",
  },
  {
    id: 10,
    name: "Blue fox",
    type: "visa",
    worth: "$495.61",
    supplierName: "Paucek-Kuvalis",
    createAt: "4/26/2021",
  },
  {
    id: 11,
    name: "Cape white-eye",
    type: "mastercard",
    worth: "$176.70",
    supplierName: "Daugherty-Keebler",
    createAt: "11/18/2020",
  },
  {
    id: 12,
    name: "Dove, white-winged",
    type: "visa",
    worth: "$106.58",
    supplierName: "Stanton-Stark",
    createAt: "2/16/2021",
  },
  {
    id: 13,
    name: "Osprey",
    type: "visa",
    worth: "$172.06",
    supplierName: "Torp and Sons",
    createAt: "12/19/2020",
  },
  {
    id: 14,
    name: "Mule deer",
    type: "mastercard",
    worth: "$4.87",
    supplierName: "McDermott-McKenzie",
    createAt: "3/23/2021",
  },
  {
    id: 15,
    name: "Nutcracker, clark's",
    type: "visa",
    worth: "$518.04",
    supplierName: "Greenfelder, Buckridge and Yost",
    createAt: "3/4/2021",
  },
  {
    id: 16,
    name: "Wombat, southern hairy-nosed",
    type: "visa",
    worth: "$3.83",
    supplierName: "Christiansen, Kunze and Champlin",
    createAt: "9/1/2021",
  },
  {
    id: 17,
    name: "Civet, small-toothed palm",
    type: "americanexpress",
    worth: "$199.40",
    supplierName: "Satterfield, Jacobs and Carroll",
    createAt: "6/26/2021",
  },
  {
    id: 18,
    name: "Downy woodpecker",
    type: "mastercard",
    worth: "$382.90",
    supplierName: "Rau-Wisoky",
    createAt: "5/29/2021",
  },
  {
    id: 19,
    name: "Sable antelope",
    type: "visa",
    worth: "$157.39",
    supplierName: "Deckow, Ratke and Koepp",
    createAt: "4/28/2021",
  },
  {
    id: 20,
    name: "Crowned hawk-eagle",
    type: "mastercard",
    worth: "$98.07",
    supplierName: "Jones-Crooks",
    createAt: "5/3/2021",
  },
];
